# Generated by Django 5.0.6 on 2024-05-30 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taskCategory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskTittle', models.CharField(max_length=100)),
                ('taskDescription', models.TextField()),
                ('is_completed', models.BooleanField(default=False)),
                ('taskDate', models.DateTimeField(default=datetime.datetime(2024, 5, 30, 23, 9, 38, 215650))),
                ('category', models.ManyToManyField(to='taskCategory.taskcategory')),
            ],
        ),
    ]
