# Generated by Django 5.0.6 on 2024-05-30 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskModel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='taskDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
